// FitOS — Food Database (160+ items, Indian + Global)
const FOOD_DB = [
  // ── Indian staples ───────────────────────────────────────
  { id:'f001', name:'Dal Tadka',               serving:'1 bowl (200g)', cal:184, p:10.8,c:27, fat:4.2, cat:'Indian',   aliases:['dal','toor dal','yellow dal','arhar'] },
  { id:'f002', name:'Roti (Whole Wheat)',       serving:'1 roti (40g)', cal:104, p:3.5, c:21, fat:0.5, cat:'Indian',   aliases:['chapati','phulka','fulka'] },
  { id:'f003', name:'Basmati Rice (cooked)',    serving:'1 cup (180g)', cal:234, p:4.9, c:50, fat:0.5, cat:'Indian',   aliases:['rice','white rice','chawal'] },
  { id:'f004', name:'Paneer',                  serving:'100g',         cal:265, p:18.3,c:3.7,fat:20.8,cat:'Indian',   aliases:['cottage cheese','desi paneer'] },
  { id:'f005', name:'Rajma Masala',            serving:'1 bowl (200g)',cal:254, p:17.4,c:45.6,fat:1,   cat:'Indian',   aliases:['kidney beans','rajma'] },
  { id:'f006', name:'Chole Bhature',           serving:'1 plate',      cal:550, p:15, c:72,  fat:22,   cat:'Indian',   aliases:['chana masala','chickpea'] },
  { id:'f007', name:'Aloo Paratha',            serving:'1 paratha(100g)',cal:260,p:5, c:38,  fat:10,   cat:'Indian',   aliases:['paratha','stuffed roti'] },
  { id:'f008', name:'Idli',                    serving:'2 idlis (100g)',cal:85, p:3.3,c:17,  fat:0.5,  cat:'South Indian',aliases:['idly','rice cake'] },
  { id:'f009', name:'Sambar',                  serving:'1 cup (200g)', cal:110, p:5.6,c:16,  fat:3,    cat:'South Indian',aliases:['vegetable stew'] },
  { id:'f010', name:'Dosa (Plain)',            serving:'1 large (120g)',cal:198,p:4.8,c:34.8,fat:4.8,  cat:'South Indian',aliases:['rice crepe','plain dosa'] },
  { id:'f011', name:'Masala Dosa',            serving:'1 (220g)',      cal:385,p:8, c:60,   fat:13,   cat:'South Indian',aliases:['stuffed dosa'] },
  { id:'f012', name:'Poha',                   serving:'1 plate (150g)',cal:195,p:4.5,c:42,  fat:1.5,  cat:'Indian',   aliases:['flattened rice','chivda','beaten rice'] },
  { id:'f013', name:'Upma',                   serving:'1 plate (150g)',cal:240,p:6, c:40.5, fat:6,    cat:'Indian',   aliases:['sooji upma','semolina'] },
  { id:'f014', name:'Moong Dal (cooked)',     serving:'1 bowl (200g)', cal:210,p:14.4,c:36, fat:0.8,  cat:'Indian',   aliases:['green gram dal','mung dal'] },
  { id:'f015', name:'Palak Paneer',           serving:'1 serving (200g)',cal:330,p:16,c:14, fat:24,   cat:'Indian',   aliases:['spinach paneer','saag paneer'] },
  { id:'f016', name:'Butter Chicken',         serving:'1 serving (200g)',cal:370,p:30,c:12, fat:24,   cat:'Indian',   aliases:['murgh makhani','chicken curry'] },
  { id:'f017', name:'Biryani (Chicken)',       serving:'1 plate (350g)',cal:560,p:35,c:70,  fat:16,   cat:'Indian',   aliases:['chicken biryani'] },
  { id:'f018', name:'Biryani (Veg)',           serving:'1 plate (300g)',cal:430,p:10,c:78,  fat:10,   cat:'Indian',   aliases:['vegetable biryani'] },
  { id:'f019', name:'Khichdi',               serving:'1 bowl (250g)', cal:280, p:11,c:52,  fat:4.5,  cat:'Indian',   aliases:['rice and dal','moong khichdi'] },
  { id:'f020', name:'Curd / Dahi (Full fat)', serving:'100g',          cal:61, p:3.1,c:4.7, fat:3.4,  cat:'Indian',   aliases:['yogurt','dahi','curd'] },
  { id:'f021', name:'Lassi (Plain)',           serving:'1 glass (200ml)',cal:120,p:5,c:14,  fat:5,    cat:'Indian',   aliases:['buttermilk','sweet lassi'] },
  { id:'f022', name:'Puri',                   serving:'2 puris (60g)', cal:204, p:3.6,c:24, fat:10.8, cat:'Indian',   aliases:['poori','fried bread'] },
  { id:'f023', name:'Methi Paratha',          serving:'1 paratha (80g)',cal:220, p:5.2,c:32, fat:8,   cat:'Indian',   aliases:['fenugreek paratha'] },
  { id:'f024', name:'Uttapam',               serving:'1 (130g)',       cal:180, p:4.5,c:33, fat:4.2,  cat:'South Indian',aliases:['uthappam','rice pancake'] },
  { id:'f025', name:'Vada Pav',              serving:'1',              cal:286, p:7,c:44,   fat:9.5,  cat:'Indian',   aliases:['Indian burger','mumbai vada pav'] },
  { id:'f026', name:'Pav Bhaji',             serving:'1 plate',        cal:420, p:10,c:60,  fat:16,   cat:'Indian',   aliases:['pav bhaji'] },
  { id:'f027', name:'Aloo Gobi',             serving:'1 serving (200g)',cal:180,p:5,c:28,  fat:6,    cat:'Indian',   aliases:['potato cauliflower'] },
  { id:'f028', name:'Sprouts (mixed, cooked)',serving:'100g',           cal:95, p:7.5,c:16, fat:0.4,  cat:'Indian',   aliases:['moong sprouts','bean sprouts'] },
  { id:'f029', name:'Sabudana Khichdi',       serving:'1 bowl (200g)', cal:350, p:4,c:70,  fat:8,    cat:'Indian',   aliases:['sago khichdi','tapioca khichdi'] },
  { id:'f030', name:'Halwa (Sooji)',          serving:'1 serving (100g)',cal:350,p:4,c:50, fat:15,   cat:'Indian',   aliases:['sheera','suji halwa'] },

  // ── Proteins ─────────────────────────────────────────────
  { id:'f031', name:'Chicken Breast (cooked)',serving:'100g',           cal:165,p:31, c:0,  fat:3.6,  cat:'Protein',  aliases:['grilled chicken','chicken'] },
  { id:'f032', name:'Chicken Thigh (cooked)', serving:'100g',           cal:209,p:26, c:0,  fat:11,   cat:'Protein',  aliases:['chicken thigh','dark meat'] },
  { id:'f033', name:'Whole Egg',              serving:'1 egg (50g)',    cal:72, p:6,  c:0.6,fat:5,    cat:'Protein',  aliases:['egg','anda','boiled egg'] },
  { id:'f034', name:'Egg Whites',             serving:'100g',           cal:52, p:11, c:0.7,fat:0.2,  cat:'Protein',  aliases:['egg white','albumen'] },
  { id:'f035', name:'Tuna (canned in water)', serving:'100g',           cal:116,p:25.5,c:0, fat:1,   cat:'Protein',  aliases:['tuna fish','tinned tuna'] },
  { id:'f036', name:'Salmon (cooked)',        serving:'100g',           cal:208,p:20, c:0,  fat:13,   cat:'Protein',  aliases:['salmon fish','atlantic salmon'] },
  { id:'f037', name:'Whey Protein (scoop)',   serving:'30g scoop',      cal:120,p:24, c:3,  fat:2,    cat:'Supplement',aliases:['protein powder','whey','isolate'] },
  { id:'f038', name:'Tofu (firm)',            serving:'100g',           cal:76, p:8,  c:1.9,fat:4.8,  cat:'Protein',  aliases:['soy protein','bean curd'] },
  { id:'f039', name:'Tempeh',                serving:'100g',           cal:193,p:19, c:9,  fat:11,   cat:'Protein',  aliases:['fermented soy'] },
  { id:'f040', name:'Lentils (cooked)',       serving:'100g',           cal:116,p:9,  c:20, fat:0.4,  cat:'Protein',  aliases:['masoor dal','red lentils'] },
  { id:'f041', name:'Black Beans (cooked)',   serving:'100g',           cal:132,p:8.9,c:24, fat:0.5,  cat:'Protein',  aliases:['black beans','kala rajma'] },
  { id:'f042', name:'Chickpeas (cooked)',     serving:'100g',           cal:164,p:8.9,c:27, fat:2.6,  cat:'Protein',  aliases:['chana','garbanzo','kabuli chana'] },
  { id:'f043', name:'Sardines (canned)',      serving:'100g',           cal:208,p:24.6,c:0, fat:11.5, cat:'Protein',  aliases:['sardine','small fish'] },
  { id:'f044', name:'Cottage Cheese (Low Fat)',serving:'100g',          cal:72, p:12.4,c:2.7,fat:1,   cat:'Protein',  aliases:['low fat paneer','skimmed cottage cheese'] },
  { id:'f045', name:'Greek Yoghurt (plain)',  serving:'100g',           cal:59, p:10, c:3.6,fat:0.4,  cat:'Dairy',    aliases:['greek yogurt','strained yogurt'] },

  // ── Carbs / Grains ────────────────────────────────────────
  { id:'f046', name:'Brown Rice (cooked)',    serving:'1 cup (195g)',   cal:216,p:5,  c:45, fat:1.8,  cat:'Grains',   aliases:['brown rice'] },
  { id:'f047', name:'Oats (rolled)',          serving:'100g dry',       cal:389,p:17, c:66, fat:7,    cat:'Grains',   aliases:['oatmeal','porridge','rolled oats'] },
  { id:'f048', name:'Quinoa (cooked)',        serving:'100g',           cal:120,p:4.4,c:21.3,fat:1.9, cat:'Grains',   aliases:['quinoa'] },
  { id:'f049', name:'Sweet Potato (boiled)', serving:'100g',           cal:90, p:2,  c:21, fat:0.1,  cat:'Vegetables',aliases:['shakarkandi','sweet potato'] },
  { id:'f050', name:'Bread (whole wheat)',    serving:'1 slice (30g)', cal:80, p:4,  c:14, fat:1.5,  cat:'Grains',   aliases:['whole grain bread','multigrain bread'] },
  { id:'f051', name:'Banana',                serving:'1 medium (120g)',cal:105,p:1.3,c:27, fat:0.4,  cat:'Fruits',   aliases:['kela','banana'] },
  { id:'f052', name:'White Potato (boiled)', serving:'100g',           cal:87, p:1.9,c:20, fat:0.1,  cat:'Vegetables',aliases:['aloo','potato'] },
  { id:'f053', name:'Pasta (cooked)',         serving:'100g',           cal:131,p:5,  c:25, fat:1.1,  cat:'Grains',   aliases:['spaghetti','penne','macaroni'] },
  { id:'f054', name:'Bread (white)',          serving:'1 slice (28g)', cal:77, p:2.7,c:14.3,fat:1,   cat:'Grains',   aliases:['white bread','sandwich bread'] },
  { id:'f055', name:'Corn / Maize (boiled)', serving:'100g',           cal:96, p:3.4,c:21, fat:1.5,  cat:'Grains',   aliases:['corn','makai','sweet corn'] },
  { id:'f056', name:'Apple',                 serving:'1 medium (180g)',cal:94, p:0.5,c:25, fat:0.3,  cat:'Fruits',   aliases:['apple','seb'] },
  { id:'f057', name:'Mango (Alfonso)',        serving:'1 cup (165g)',   cal:99, p:1.4,c:25, fat:0.6,  cat:'Fruits',   aliases:['aam','mango'] },
  { id:'f058', name:'Dates (Medjool)',        serving:'2 dates (48g)',  cal:133,p:0.8,c:36, fat:0.1,  cat:'Fruits',   aliases:['khajur','dates'] },

  // ── Fats ─────────────────────────────────────────────────
  { id:'f059', name:'Almonds',               serving:'28g (~23)',      cal:164,p:6,  c:6,  fat:14,   cat:'Nuts',     aliases:['badam','almond'] },
  { id:'f060', name:'Peanut Butter (natural)',serving:'2 tbsp (32g)',  cal:188,p:8,  c:6.9,fat:16,   cat:'Nuts',     aliases:['peanut butter','groundnut butter'] },
  { id:'f061', name:'Avocado',               serving:'100g',           cal:160,p:2,  c:9,  fat:15,   cat:'Fruits',   aliases:['avocado'] },
  { id:'f062', name:'Olive Oil',             serving:'1 tbsp (14g)',   cal:119,p:0,  c:0,  fat:14,   cat:'Fats',     aliases:['EVOO','extra virgin olive oil'] },
  { id:'f063', name:'Ghee',                  serving:'1 tsp (5g)',     cal:44, p:0,  c:0,  fat:5,    cat:'Indian',   aliases:['clarified butter','desi ghee'] },
  { id:'f064', name:'Coconut Oil',           serving:'1 tbsp (14g)',   cal:121,p:0,  c:0,  fat:13.5, cat:'Fats',     aliases:['coconut oil','nariyal tel'] },
  { id:'f065', name:'Walnuts',               serving:'28g',            cal:185,p:4.3,c:3.9,fat:18.5, cat:'Nuts',     aliases:['akhrot','walnut'] },
  { id:'f066', name:'Cashews',               serving:'28g',            cal:157,p:5.2,c:9.3,fat:12.4, cat:'Nuts',     aliases:['kaju','cashew'] },
  { id:'f067', name:'Flaxseeds',             serving:'1 tbsp (10g)',   cal:55, p:1.9,c:3,  fat:4.3,  cat:'Seeds',    aliases:['flax seeds','alsi'] },
  { id:'f068', name:'Chia Seeds',            serving:'1 tbsp (10g)',   cal:49, p:1.7,c:4.4,fat:3.1,  cat:'Seeds',    aliases:['chia'] },

  // ── Dairy ─────────────────────────────────────────────────
  { id:'f069', name:'Milk (Toned, 3%)',       serving:'1 glass (200ml)',cal:116,p:6.4,c:9.4,fat:6.8,  cat:'Dairy',    aliases:['doodh','milk'] },
  { id:'f070', name:'Milk (Full Fat)',         serving:'1 glass (200ml)',cal:130,p:6.4,c:9.4,fat:8,    cat:'Dairy',    aliases:['whole milk','full cream milk'] },
  { id:'f071', name:'Cheddar Cheese',          serving:'30g slice',     cal:121,p:7.5,c:0.1,fat:10,   cat:'Dairy',    aliases:['cheese slice','cheddar'] },
  { id:'f072', name:'Butter',                  serving:'1 tbsp (14g)',  cal:102,p:0.1,c:0,  fat:11.5, cat:'Dairy',    aliases:['butter','makhan'] },
  { id:'f073', name:'Sour Cream',              serving:'100g',          cal:198,p:2.4,c:4.6,fat:19.4, cat:'Dairy',    aliases:['sour cream'] },

  // ── Vegetables ────────────────────────────────────────────
  { id:'f074', name:'Broccoli (cooked)',       serving:'100g',          cal:35, p:2.4,c:7.2,fat:0.4,  cat:'Vegetables',aliases:['broccoli'] },
  { id:'f075', name:'Spinach (raw)',           serving:'100g',          cal:23, p:2.9,c:3.6,fat:0.4,  cat:'Vegetables',aliases:['palak','spinach'] },
  { id:'f076', name:'Tomato',                  serving:'1 medium (120g)',cal:22,p:1.1,c:4.7,fat:0.2,  cat:'Vegetables',aliases:['tamatar','tomato'] },
  { id:'f077', name:'Carrot',                  serving:'1 medium (80g)',cal:33, p:0.7,c:8,  fat:0.2,  cat:'Vegetables',aliases:['gajar','carrot'] },
  { id:'f078', name:'Cucumber',                serving:'100g',          cal:15, p:0.7,c:3.6,fat:0.1,  cat:'Vegetables',aliases:['kheera','kakdi','cucumber'] },
  { id:'f079', name:'Capsicum (Bell Pepper)',  serving:'1 medium (120g)',cal:31,p:1.2,c:6.4,fat:0.3,  cat:'Vegetables',aliases:['shimla mirch','bell pepper'] },
  { id:'f080', name:'Mushrooms (cooked)',       serving:'100g',          cal:28, p:3,  c:5.3,fat:0.2,  cat:'Vegetables',aliases:['mushroom','champignon'] },
  { id:'f081', name:'Cauliflower',              serving:'100g',          cal:25, p:1.9,c:5,  fat:0.3,  cat:'Vegetables',aliases:['gobhi','phool gobhi','cauliflower'] },
  { id:'f082', name:'Green Peas (cooked)',      serving:'100g',          cal:84, p:5.4,c:15.6,fat:0.4, cat:'Vegetables',aliases:['matar','peas'] },

  // ── Beverages & Supplements ───────────────────────────────
  { id:'f083', name:'Creatine Monohydrate',    serving:'5g',            cal:0,  p:0,  c:0,  fat:0,    cat:'Supplement',aliases:['creatine'] },
  { id:'f084', name:'BCAA Powder',             serving:'5g',            cal:20, p:5,  c:0,  fat:0,    cat:'Supplement',aliases:['BCAA','amino acids'] },
  { id:'f085', name:'Protein Bar (generic)',   serving:'1 bar (50g)',   cal:200,p:20, c:20, fat:6,    cat:'Supplement',aliases:['protein bar','snack bar'] },
  { id:'f086', name:'Mass Gainer (scoop)',     serving:'100g',          cal:380,p:25, c:60, fat:5,    cat:'Supplement',aliases:['mass gainer','weight gainer'] },
  { id:'f087', name:'Coconut Water',           serving:'1 cup (240ml)', cal:46, p:1.7,c:8.9,fat:0.5,  cat:'Beverages', aliases:['nariyal pani','coconut water'] },
  { id:'f088', name:'Orange Juice (fresh)',    serving:'1 glass (200ml)',cal:90,p:1.4,c:20.9,fat:0.2, cat:'Beverages', aliases:['OJ','orange juice','mosambi'] },

  // ── Fast food & packaged ──────────────────────────────────
  { id:'f089', name:'Samosa',                  serving:'2 samosas (100g)',cal:270,p:5,c:32, fat:14,  cat:'Snacks',   aliases:['samosa'] },
  { id:'f090', name:'Biscuit (Marie)',         serving:'4 biscuits (30g)',cal:130,p:2.4,c:22,fat:3.6, cat:'Snacks',   aliases:['marie biscuit','glucose biscuit'] },
  { id:'f091', name:'Bread Omelette',          serving:'1 serving',      cal:280,p:14,c:24, fat:13,  cat:'Indian',   aliases:['egg omelette bread'] },
  { id:'f092', name:'Peanuts (roasted)',        serving:'30g',            cal:176,p:7.5,c:4.6,fat:14.3,cat:'Nuts',    aliases:['moongphali','groundnut','peanut'] },

  // ── More Indian ───────────────────────────────────────────
  { id:'f093', name:'Chaat (Papdi)',           serving:'1 plate (150g)', cal:300,p:8,c:40,  fat:12,  cat:'Indian',   aliases:['papdi chaat','Indian chaat'] },
  { id:'f094', name:'Dhokla',                 serving:'4 pieces (100g)', cal:160,p:6,c:26,  fat:4,   cat:'Indian',   aliases:['dhokla','gujarati snack'] },
  { id:'f095', name:'Mathri',                 serving:'3 pieces (30g)',  cal:150,p:2.4,c:17, fat:8,   cat:'Indian',   aliases:['mathri','Indian cracker'] },
  { id:'f096', name:'Kadhi Pakora',           serving:'1 bowl (200g)',   cal:220,p:6,c:26,  fat:11,  cat:'Indian',   aliases:['kadhi','yogurt curry'] },
  { id:'f097', name:'Matar Paneer',           serving:'1 serving (200g)',cal:380,p:16,c:18, fat:28,  cat:'Indian',   aliases:['peas paneer'] },
  { id:'f098', name:'Jeera Rice',             serving:'1 cup (200g)',    cal:290,p:5,c:60,  fat:5,   cat:'Indian',   aliases:['cumin rice','jeera rice'] },
  { id:'f099', name:'Dal Makhani',            serving:'1 bowl (200g)',   cal:310,p:13,c:38, fat:12,  cat:'Indian',   aliases:['black dal','mah ki dal'] },
  { id:'f100', name:'Aloo Tikki',             serving:'2 pieces (100g)', cal:220,p:3.5,c:34, fat:8,  cat:'Indian',   aliases:['potato tikki','aloo tikki'] },

  // ── More Indian & Regional ────────────────────────────────
  { id:'f101', name:'Pongal (Ven)',            serving:'1 bowl (200g)',   cal:260,p:7,c:46,  fat:6,   cat:'South Indian',aliases:['ven pongal','khichdi'] },
  { id:'f102', name:'Appam',                  serving:'2 appams (100g)', cal:170,p:4,c:34,  fat:2.5, cat:'South Indian',aliases:['hoppers','rice appam'] },
  { id:'f103', name:'Rasam',                  serving:'1 cup (200ml)',   cal:45, p:2,c:8,   fat:1,   cat:'South Indian',aliases:['tomato rasam','pepper water'] },
  { id:'f104', name:'Kootu',                  serving:'1 serving (150g)',cal:180,p:6,c:22,  fat:8,   cat:'South Indian',aliases:['vegetable kootu'] },
  { id:'f105', name:'Curd Rice',              serving:'1 bowl (200g)',   cal:220,p:7,c:36,  fat:6,   cat:'South Indian',aliases:['thayir sadam','yogurt rice'] },
  { id:'f106', name:'Bisi Bele Bath',         serving:'1 bowl (200g)',   cal:280,p:8,c:48,  fat:7,   cat:'South Indian',aliases:['bisibelebath','Karnataka rice'] },
  { id:'f107', name:'Pulihora',               serving:'1 plate (200g)',  cal:310,p:6,c:58,  fat:7,   cat:'South Indian',aliases:['tamarind rice','puliyogare'] },
  { id:'f108', name:'Hyderabadi Biryani',     serving:'1 plate (350g)',  cal:620,p:38,c:72, fat:18,  cat:'Indian',   aliases:['mutton biryani','dum biryani'] },
  { id:'f109', name:'Sheer Khurma',           serving:'1 bowl (150ml)',  cal:280,p:8,c:38,  fat:11,  cat:'Indian',   aliases:['sheer korma','Eid dessert'] },
  { id:'f110', name:'Haleem',                 serving:'1 bowl (200g)',   cal:350,p:28,c:28, fat:14,  cat:'Indian',   aliases:['slow-cooked meat porridge'] },
  { id:'f111', name:'Nihari',                 serving:'1 bowl (250g)',   cal:420,p:34,c:16, fat:26,  cat:'Indian',   aliases:['beef nihari','mutton stew'] },
  { id:'f112', name:'Chapli Kebab',           serving:'2 pieces (100g)', cal:260,p:20,c:8,  fat:17,  cat:'Indian',   aliases:['seekh kebab variant'] },
  { id:'f113', name:'Shami Kebab',            serving:'2 pieces (80g)',  cal:210,p:16,c:10, fat:12,  cat:'Indian',   aliases:['dal kebab'] },
  { id:'f114', name:'Mutton Korma',           serving:'1 serving (200g)',cal:440,p:32,c:10, fat:30,  cat:'Indian',   aliases:['gosht korma','lamb korma'] },
  { id:'f115', name:'Fish Curry (South)',     serving:'1 serving (200g)',cal:280,p:28,c:8,  fat:15,  cat:'Indian',   aliases:['fish curry','machli curry'] },
  { id:'f116', name:'Prawn Masala',           serving:'1 serving (150g)',cal:220,p:24,c:6,  fat:11,  cat:'Indian',   aliases:['jhinga masala','shrimp curry'] },
  { id:'f117', name:'Pani Puri Water',        serving:'6 pieces',        cal:120,p:3,c:22,  fat:2,   cat:'Indian',   aliases:['gol gappa','puchka','phuchka'] },
  { id:'f118', name:'Bhel Puri',              serving:'1 plate (150g)',  cal:240,p:6,c:42,  fat:6,   cat:'Indian',   aliases:['puffed rice snack'] },
  { id:'f119', name:'Sev Puri',              serving:'1 plate (120g)',  cal:280,p:6,c:38,  fat:12,  cat:'Indian',   aliases:['sev chaat'] },
  { id:'f120', name:'Misal Pav',              serving:'1 plate',         cal:380,p:14,c:55, fat:11,  cat:'Indian',   aliases:['misal','sprouted curry'] },

  // ── Global Foods Expanded ─────────────────────────────────
  { id:'f121', name:'Pasta (cooked)',          serving:'1 cup (180g)',    cal:220,p:8,c:43,  fat:1.3, cat:'Global',   aliases:['spaghetti','penne','pasta'] },
  { id:'f122', name:'Pizza (cheese)',          serving:'1 slice (100g)',  cal:266,p:11,c:33, fat:10,  cat:'Global',   aliases:['pizza slice'] },
  { id:'f123', name:'Burger',                 serving:'1 medium',        cal:490,p:25,c:40, fat:22,  cat:'Global',   aliases:['hamburger','cheeseburger'] },
  { id:'f124', name:'French Fries',           serving:'1 medium (130g)', cal:378,p:4,c:48,  fat:20,  cat:'Global',   aliases:['fries','chips','potato fries'] },
  { id:'f125', name:'Sushi (salmon roll)',     serving:'6 pieces (150g)', cal:304,p:13,c:42, fat:7,   cat:'Japanese', aliases:['sushi roll','maki'] },
  { id:'f126', name:'Ramen',                  serving:'1 bowl (450ml)',  cal:510,p:22,c:73, fat:13,  cat:'Japanese', aliases:['Japanese noodle soup'] },
  { id:'f127', name:'Pad Thai',               serving:'1 plate (300g)',  cal:520,p:22,c:62, fat:18,  cat:'Thai',     aliases:['Thai noodles'] },
  { id:'f128', name:'Tacos (chicken)',         serving:'2 tacos',         cal:340,p:22,c:30, fat:12,  cat:'Mexican',  aliases:['taco','Mexican tacos'] },
  { id:'f129', name:'Burrito Bowl',           serving:'1 bowl (450g)',   cal:620,p:32,c:78, fat:18,  cat:'Mexican',  aliases:['chipotle bowl'] },
  { id:'f130', name:'Hummus',                 serving:'100g',            cal:166,p:7.9,c:14,fat:9.6, cat:'Middle Eastern',aliases:['chickpea dip'] },
  { id:'f131', name:'Falafel (3 pieces)',     serving:'75g',             cal:225,p:9,c:22,  fat:11,  cat:'Middle Eastern',aliases:['fried chickpea balls'] },
  { id:'f132', name:'Shawarma (chicken)',     serving:'1 wrap',          cal:540,p:36,c:48, fat:18,  cat:'Middle Eastern',aliases:['doner kebab','wrap'] },
  { id:'f133', name:'Udon Noodles (cooked)',  serving:'1 bowl (200g)',   cal:280,p:9,c:57,  fat:1,   cat:'Japanese', aliases:['udon','Japanese wheat noodles'] },
  { id:'f134', name:'Miso Soup',              serving:'1 cup (240ml)',   cal:40, p:3,c:5,   fat:1.5, cat:'Japanese', aliases:['Japanese soup','miso'] },
  { id:'f135', name:'Pho (beef)',             serving:'1 bowl (500ml)',  cal:420,p:30,c:52, fat:10,  cat:'Vietnamese',aliases:['Vietnamese noodle soup'] },
  { id:'f136', name:'Spring Roll (fried)',    serving:'2 pieces (100g)', cal:220,p:5,c:26,  fat:11,  cat:'Chinese',  aliases:['egg roll'] },
  { id:'f137', name:'Dim Sum (3 pcs)',        serving:'3 pieces (90g)',  cal:180,p:9,c:22,  fat:6,   cat:'Chinese',  aliases:['yum cha','har gow'] },
  { id:'f138', name:'Fried Rice (egg)',       serving:'1 cup (200g)',    cal:340,p:10,c:52, fat:10,  cat:'Chinese',  aliases:['egg fried rice'] },
  { id:'f139', name:'Naan Bread',             serving:'1 large (90g)',   cal:262,p:8.7,c:45,fat:5.1, cat:'Indian',   aliases:['naan','Indian flatbread'] },
  { id:'f140', name:'Lasagna',               serving:'1 slice (250g)',  cal:440,p:22,c:42, fat:20,  cat:'Global',   aliases:['Italian pasta bake'] },

  // ── Snacks & Fast Food ────────────────────────────────────
  { id:'f141', name:'Potato Chips (plain)',   serving:'28g (1oz)',       cal:152,p:2,c:15,  fat:10,  cat:'Snack',    aliases:['crisps','lays','chips'] },
  { id:'f142', name:'Popcorn (air-popped)',   serving:'3 cups (28g)',    cal:93, p:3,c:19,  fat:1,   cat:'Snack',    aliases:['popcorn'] },
  { id:'f143', name:'Dark Chocolate (70%+)', serving:'30g',             cal:170,p:2.5,c:14,fat:12,  cat:'Snack',    aliases:['dark choc','bitter chocolate'] },
  { id:'f144', name:'Trail Mix',              serving:'30g',             cal:160,p:4,c:14,  fat:10,  cat:'Snack',    aliases:['nut mix','mixed nuts'] },
  { id:'f145', name:'Protein Bar',            serving:'1 bar (60g)',     cal:210,p:20,c:22, fat:7,   cat:'Supplement',aliases:['quest bar','rx bar','protein snack'] },
  { id:'f146', name:'Rice Cakes',             serving:'2 cakes (18g)',   cal:70, p:1.4,c:15,fat:0.5, cat:'Snack',    aliases:['rice crackers'] },
  { id:'f147', name:'Nachos (plain)',         serving:'56g',             cal:270,p:4,c:36,  fat:13,  cat:'Snack',    aliases:['tortilla chips'] },
  { id:'f148', name:'Granola Bar',            serving:'1 bar (47g)',     cal:200,p:4,c:30,  fat:8,   cat:'Snack',    aliases:['oat bar','cereal bar'] },
  { id:'f149', name:'Energy Drink (sugar-free)',serving:'1 can (250ml)', cal:10, p:0,c:1,   fat:0,   cat:'Beverage',  aliases:['red bull zero','monster ultra'] },
  { id:'f150', name:'Black Coffee',           serving:'1 cup (240ml)',   cal:5,  p:0.3,c:0, fat:0,   cat:'Beverage',  aliases:['americano','espresso','filter coffee'] },

  // ── Fruits Expanded ───────────────────────────────────────
  { id:'f151', name:'Watermelon',             serving:'2 cups (280g)',   cal:85, p:1.7,c:21, fat:0.4, cat:'Fruit',    aliases:['tarbuz','watermelon'] },
  { id:'f152', name:'Pomegranate',            serving:'1 cup (174g)',    cal:144,p:3,c:33,  fat:2,   cat:'Fruit',    aliases:['anar','pomegranate seeds'] },
  { id:'f153', name:'Guava',                  serving:'1 medium (100g)', cal:68, p:2.6,c:14, fat:1,   cat:'Fruit',    aliases:['amrood'] },
  { id:'f154', name:'Papaya',                 serving:'1 cup (145g)',    cal:62, p:0.7,c:16, fat:0.4, cat:'Fruit',    aliases:['papita','pawpaw'] },
  { id:'f155', name:'Litchi',                 serving:'10 fruits (100g)',cal:66, p:0.8,c:17, fat:0.4, cat:'Fruit',    aliases:['lychee'] },
  { id:'f156', name:'Chickoo (Sapodilla)',     serving:'1 medium (100g)', cal:83, p:0.4,c:20, fat:1.1, cat:'Fruit',    aliases:['chiku','sapota'] },
  { id:'f157', name:'Jackfruit (ripe)',       serving:'1 cup (165g)',    cal:157,p:2.8,c:38, fat:1,   cat:'Fruit',    aliases:['kathal','chakka'] },
  { id:'f158', name:'Custard Apple',          serving:'1 medium (200g)', cal:170,p:3,c:42,  fat:0.8, cat:'Fruit',    aliases:['sitaphal','sugar apple'] },
  { id:'f159', name:'Starfruit (Carambola)',   serving:'1 medium (90g)',  cal:28, p:0.9,c:6,  fat:0.3, cat:'Fruit',    aliases:['star fruit'] },
  { id:'f160', name:'Dragon Fruit',           serving:'100g',            cal:60, p:1.2,c:13, fat:0,   cat:'Fruit',    aliases:['pitaya'] },

  // ── Vegetables Expanded ───────────────────────────────────
  { id:'f161', name:'Bitter Gourd (Karela)',  serving:'1 cup (94g)',     cal:20, p:1,c:4,   fat:0.2, cat:'Vegetable',aliases:['bitter melon','karela'] },
  { id:'f162', name:'Drumstick (Moringa pod)',serving:'100g',            cal:37, p:2.1,c:8,  fat:0.1, cat:'Vegetable',aliases:['sahjan','moringa','sehjan'] },
  { id:'f163', name:'Lotus Root (Kamal Kakdi)',serving:'100g',           cal:74, p:2.6,c:17, fat:0.1, cat:'Vegetable',aliases:['lotus stem','kamal kakdi'] },
  { id:'f164', name:'Raw Papaya',             serving:'100g',            cal:32, p:1.3,c:7,  fat:0.6, cat:'Vegetable',aliases:['kacha papita'] },
  { id:'f165', name:'Bottle Gourd (Lauki)',   serving:'1 cup (145g)',    cal:26, p:1.2,c:5,  fat:0.5, cat:'Vegetable',aliases:['lauki','doodhi','ghiya'] },
  { id:'f166', name:'Taro Root (Arbi)',       serving:'100g (cooked)',   cal:142,p:0.5,c:34, fat:0.1, cat:'Vegetable',aliases:['arbi','colocasia'] },
  { id:'f167', name:'Green Banana (Raw)',     serving:'1 medium (100g)', cal:89, p:1.1,c:23, fat:0.3, cat:'Vegetable',aliases:['raw plantain','kela'] },
  { id:'f168', name:'Radish (Mooli)',         serving:'100g',            cal:16, p:0.7,c:3.4,fat:0.1, cat:'Vegetable',aliases:['mooli','daikon'] },
  { id:'f169', name:'Ash Gourd (Petha)',      serving:'100g',            cal:13, p:0.4,c:3,  fat:0.2, cat:'Vegetable',aliases:['white gourd','petha'] },
  { id:'f170', name:'Raw Jackfruit',          serving:'100g',            cal:51, p:3.6,c:10, fat:0.3, cat:'Vegetable',aliases:['green jackfruit','kathal curry'] },

  // ── Dairy & Alternatives ──────────────────────────────────
  { id:'f171', name:'Paneer (Low Fat)',       serving:'100g',            cal:180,p:21,c:4,  fat:9,   cat:'Dairy',    aliases:['low fat cottage cheese'] },
  { id:'f172', name:'Ghee',                  serving:'1 tsp (5g)',      cal:45, p:0,c:0,   fat:5,   cat:'Dairy',    aliases:['clarified butter','desi ghee'] },
  { id:'f173', name:'Buttermilk (Chaas)',     serving:'1 glass (200ml)', cal:40, p:3.4,c:4.8,fat:0.9,cat:'Dairy',    aliases:['chaas','lassi thin','mattha'] },
  { id:'f174', name:'Soy Milk (unsweetened)', serving:'1 cup (240ml)',   cal:80, p:7,c:4,   fat:4,   cat:'Dairy Alt',aliases:['soy drink','plant milk'] },
  { id:'f175', name:'Almond Milk (unsweet)', serving:'1 cup (240ml)',   cal:40, p:1,c:1,   fat:3,   cat:'Dairy Alt',aliases:['almond drink'] },
  { id:'f176', name:'Oat Milk',              serving:'1 cup (240ml)',   cal:120,p:3,c:16,  fat:5,   cat:'Dairy Alt',aliases:['oat drink','oatly'] },
  { id:'f177', name:'Mozzarella',            serving:'30g (1oz)',       cal:85, p:6.3,c:0.6,fat:6.3, cat:'Dairy',    aliases:['fresh mozzarella'] },
  { id:'f178', name:'Cheese (cheddar)',       serving:'30g (1oz)',       cal:113,p:7,c:0.4, fat:9.3, cat:'Dairy',    aliases:['cheddar','processed cheese'] },
  { id:'f179', name:'Skimmed Milk',          serving:'1 glass (200ml)', cal:70, p:6.8,c:9.4,fat:0.4, cat:'Dairy',    aliases:['fat-free milk','toned milk'] },
  { id:'f180', name:'Kefir (plain)',         serving:'1 cup (240ml)',   cal:110,p:9,c:12,  fat:2.5, cat:'Dairy',    aliases:['fermented milk','probiotic drink'] },

  // ── Sports & Fitness Nutrition ────────────────────────────
  { id:'f181', name:'Casein Protein',         serving:'30g scoop',       cal:110,p:24,c:4,  fat:1,   cat:'Supplement',aliases:['slow protein','casein powder','nighttime protein'] },
  { id:'f182', name:'Mass Gainer',            serving:'100g scoop',      cal:380,p:24,c:64, fat:4,   cat:'Supplement',aliases:['weight gainer','mass powder'] },
  { id:'f183', name:'BCAA (powder)',           serving:'10g',             cal:40, p:10,c:0,  fat:0,   cat:'Supplement',aliases:['branch chain amino acids'] },
  { id:'f184', name:'Creatine Monohydrate',   serving:'5g',              cal:0,  p:0,c:0,   fat:0,   cat:'Supplement',aliases:['creatine','mono creatine'] },
  { id:'f185', name:'Pre-Workout (avg)',       serving:'1 scoop (10g)',   cal:35, p:2,c:6,   fat:0,   cat:'Supplement',aliases:['pre workout','C4','NO Xplode'] },
  { id:'f186', name:'Sports Drink (Gatorade)',serving:'500ml bottle',    cal:130,p:0,c:34,  fat:0,   cat:'Beverage',  aliases:['electrolyte drink','sports drink'] },
  { id:'f187', name:'Coconut Water',          serving:'1 cup (240ml)',   cal:46, p:1.7,c:9,  fat:0.5, cat:'Beverage',  aliases:['nariyal pani','tender coconut'] },
  { id:'f188', name:'Green Tea',              serving:'1 cup (240ml)',   cal:2,  p:0,c:0,   fat:0,   cat:'Beverage',  aliases:['matcha','green tea'] },
  { id:'f189', name:'Protein Shake (milk)',   serving:'1 serving (350ml)',cal:280,p:35,c:22, fat:6,   cat:'Supplement',aliases:['whey shake','protein drink'] },
  { id:'f190', name:'Electrolyte Tablet',     serving:'1 tablet in 500ml',cal:5,p:0,c:1,   fat:0,   cat:'Supplement',aliases:['hydration tab','nuun','SIS electrolyte'] },

  // ── Grains & Cereals ──────────────────────────────────────
  { id:'f191', name:'Millet (Bajra cooked)',  serving:'1 cup (200g)',    cal:218,p:6.1,c:44, fat:1.8, cat:'Indian',   aliases:['bajra','pearl millet'] },
  { id:'f192', name:'Jowar (Sorghum cooked)', serving:'1 cup (200g)',    cal:212,p:7.7,c:44, fat:1.4, cat:'Indian',   aliases:['sorghum','cholam'] },
  { id:'f193', name:'Ragi (Finger Millet)',   serving:'1 cup (200g)',    cal:212,p:7.3,c:44, fat:1.3, cat:'Indian',   aliases:['finger millet','nachni'] },
  { id:'f194', name:'Quinoa (cooked)',         serving:'1 cup (185g)',    cal:222,p:8,c:39,  fat:3.5, cat:'Grain',    aliases:['quinoa','super grain'] },
  { id:'f195', name:'Couscous (cooked)',       serving:'1 cup (157g)',    cal:176,p:6,c:36,  fat:0.3, cat:'Grain',    aliases:['moroccan couscous'] },
  { id:'f196', name:'Buckwheat (cooked)',      serving:'1 cup (168g)',    cal:155,p:5.7,c:34, fat:1,   cat:'Grain',    aliases:['kuttu','kasha'] },
  { id:'f197', name:'Barley (cooked)',         serving:'1 cup (157g)',    cal:193,p:3.5,c:44, fat:0.7, cat:'Grain',    aliases:['jau','pearl barley'] },
  { id:'f198', name:'Corn (boiled)',           serving:'1 ear (100g)',    cal:86, p:3.3,c:18.7,fat:1.4,cat:'Grain',    aliases:['sweet corn','bhutta','maize'] },
  { id:'f199', name:'Vermicelli (seviyan)',    serving:'1 bowl (150g)',   cal:220,p:5,c:45,  fat:2,   cat:'Indian',   aliases:['seviyan','wheat noodles'] },
  { id:'f200', name:'Whole Wheat Bread',       serving:'2 slices (60g)',  cal:156,p:5.8,c:28, fat:2.4, cat:'Bakery',   aliases:['brown bread','multigrain bread','atta bread'] },
];

function searchFoods(query) {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return FOOD_DB.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.aliases.some(a => a.toLowerCase().includes(q)) ||
    f.cat.toLowerCase().includes(q)
  ).slice(0, 12);
}
